### ISSUE TITLE
deepposekit.import_deeplabcut_labeled_data()

### ISSUE THREAD

**Issue by alvarovegahd** [jgraving/DeepPoseKit#1]
Thanks so much to you and your team for building this good piece of software!

It would be good to be able to import deeplabcut labeled data, so more users can try this software without having to label data again. In deeplabcut there are no skeletons, so maybe the user would provide the h5 deeplabcut labeled data, the frames and the csv of the skeleton. I would like to help to develop code around this but would like to hear your feedback first. I have a bunch of data that would love to try asap with deepposekit.

[Pura vida,](https://en.wikipedia.org/wiki/Culture_of_Costa_Rica#Pura_vida)

**Comment by jgraving** [comment]
Thanks for your interest in helping to develop the code. I think the easiest way to proceed on your specific issue is for me to write some generic code for how to implement a h5file from scratch using a randomly generated dataset. I'll upload this to the repo and you can use it to develop a function for converting DLC data to DPK.

I also think the best way to manage contributed code for now is to create separate a contrib module similar to what TF and Keras did during early development. This allows for rapid development of new ideas that may not be fully functional without impacting the functionality of the core codebase. Then as the contributed code becomes more stable and widely used it can be moved to the core package. I'll put this together ASAP.

**Comment by jgraving** [comment]
I've created a repo at https://github.com/jgraving/deepposekit-contrib for user contributions. The notebooks folder has an example for creating dummy data (https://github.com/jgraving/deepposekit-contrib/blob/master/notebooks/dummy_data_example.ipynb), which should help with developing a function to accomplish this. Go ahead and submit a PR to the contrib repo when you've finished developing the function.

**Comment by jgraving** [comment]
We've now added a (experimental) data generator for loading DeepLabCut data (see here for example: https://github.com/jgraving/DeepPoseKit/blob/master/examples/deeplacut_data_example.ipynb). The `BaseGenerator` class is now abstracted so writing a custom generator is possible with arbitrary data formats. (see here for example: https://github.com/jgraving/DeepPoseKit/blob/master/examples/custom_data_generator.ipynb)

The `deepposekit.io` API has changed quite a bit, so check out the updated examples for more details: https://github.com/jgraving/DeepPoseKit/tree/master/examples
