### ISSUE TITLE
How to continue training a model?

### ISSUE THREAD

**Issue by davidjamespritchard** [jgraving/DeepPoseKit#10]
Hi.

I am training a model using CoLab. I reached 40 Epochs until CoLab disconnected, and I would like to use the last best model (which was saved) to continue training. I have looked but can't find advice for how to do this, but it would be really useful, especially for those of us using CoLab rather than a machine with a GPU.

Is this possible? If so, what would I need to load?

Thanks

David

**Comment by jgraving** [comment]
I just pushed a fix for loading models, so this should now work with the latest master branch (which should be installed by default when using colab). There are two things you need to do. First, make sure `optimizer=True` for the `ModelCheckpoint` callback. Saving and loading the model with the optimizer intact will take longer, but you need this information to resume training. 
E.g.: 
```python
model_checkpoint = ModelCheckpoint(
    HOME + "/deepposekit-data/datasets/fly/best_model_densenet.h5",
    monitor="val_loss",
    verbose=1,
    save_best_only=True,
    optimizer=True,
)
```

Second, when loading the model with `load_model` make sure to pass the same `datapath` and `augmenter` arguments from when you defined your `TrainingGenerator`. E.g.:
```python
from deepposekit.models import load_model

model = load_model(
    HOME + "/deepposekit-data/datasets/fly/best_model_densenet.h5",
    datapath=annotations[0],
    augmenter=augmenter
)
```

Depending on the complexity of the model it may take awhile to load with the optimizer. You should then be able to resume training with `model.fit`, but let me know if you run into trouble.

**Comment by jgraving** [comment]
I'll close this for now. Reopen it if you need more help.
