### ISSUE TITLE
Tensorflow installation issues

### ISSUE THREAD

**Issue by Philip642** [jgraving/DeepPoseKit#12]
Hi, I have still Ubuntu 18.04, use jupyter notebook and all with your provided data.

logger = Logger(validation_batch_size=10
    # filepath saves the logger data to a .h5 file
    # filepath=HOME + "/deepposekit-data/datasets/fly/log_densenet.h5"
)

The line works, but removing the # to save the data gives me this error:
File "<ipython-input-40-ffce7bf68581>", line 3
    filepath=HOME + "/deepposekit-data/datasets/fly/log_densenet.h5"
           ^
SyntaxError: invalid syntax

Then I got two more errors but I don't know if they are related to the first, but their the same error. With fit the model

model.fit(
    batch_size=16,
    validation_batch_size=10,
    callbacks=callbacks,
    #epochs=1000, # Increase the number of epochs to train the model longer
    epochs=200,
    n_workers=8,
    steps_per_epoch=None,
)

and load the model
model.fit(
    batch_size=5,
    validation_batch_size=10,
    callbacks=callbacks,
    epochs=30,
    n_workers=8,
    steps_per_epoch=None,
)
where the error is

AbortedError                              Traceback (most recent call last)
<ipython-input-39-8c07752fea11> in <module>
      6     epochs=200,
      7     n_workers=8,
----> 8     steps_per_epoch=None,
      9 )

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/deepposekit/models/engine.py in fit(self, batch_size, validation_batch_size, callbacks, epochs, use_multiprocessing, n_workers, steps_per_epoch, **kwargs)
    172             callbacks=activated_callbacks,
    173             validation_data=validation_generator,
--> 174             **kwargs
    175         )
    176 

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1431         shuffle=shuffle,
   1432         initial_epoch=initial_epoch,
-> 1433         steps_name='steps_per_epoch')
   1434 
   1435   def evaluate_generator(self,

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    262 
    263       is_deferred = not model._is_compiled
--> 264       batch_outs = batch_function(*batch_data)
    265       if not isinstance(batch_outs, list):
    266         batch_outs = [batch_outs]

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1173       self._update_sample_weight_modes(sample_weights=sample_weights)
   1174       self._make_train_function()
-> 1175       outputs = self.train_function(ins)  # pylint: disable=not-callable
   1176 
   1177     if reset_metrics:

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   3290 
   3291     fetched = self._callable_fn(*array_vals,
-> 3292                                 run_metadata=self.run_metadata)
   3293     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3294     output_structure = nest.pack_sequence_as(

~/anaconda3/envs/whipspider/lib/python3.7/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

AbortedError: Operation received an exception:Status: 5, message: could not create a view primitive descriptor, in file tensorflow/core/kernels/mkl_slice_op.cc:433
	 [[{{node Adam_1/gradients/concatenate_50_1/concat_grad/Slice_2}}]]

**Comment by eduramiba** [comment]
I found some similar errors thrown by CUBLAS and cuFFT and it was due to this tensorflow 2.0 memory growth problem https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth

Adding this code before training and evaluating fixed it:

```python
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    print(e)
```

**Comment by jgraving** [comment]
The first error is just a syntax error from not having a comma after `validation_batch_size=10,`. Not sure what's going on with the second error. I assume you mean this is happening with `model.fit` in both cases? Which version of tensorflow are you using? As @eduramiba pointed out 2.0 is still a bit buggy. The code seems to be most stable with tensorflow 1.14 (`pip install tensorflow~=1.14` or `pip install tensorflow-gpu~=1.14`). Also is tensorflow printing out anything in your jupyter notebook terminal session? Could you also post a screenshot of your nvidia-smi? (In terminal, run the command: `watch -n 0.1 nvidia-smi`)

**Comment by Philip642** [comment]
I added the code from edurambia before the "create a trainingGenerator" line and I still have the problem, even after restarting from the beginning and unchanged data from Jake.
Yes, it is happening in both cases with model.fit. I"m using tensorflow version 1.14.0
![jupyter terminal sesson](https://user-images.githubusercontent.com/55141900/66558300-a08e3d00-eb53-11e9-8df3-83916bec1bc1.png)

**Comment by Philip642** [comment]
tensorflow and nvidia-smi

**Comment by Philip642** [comment]
.
![Screenshot from 2019-10-10 11-48-53](https://user-images.githubusercontent.com/55141900/66558525-f6fb7b80-eb53-11e9-84a8-f89747b3c22e.png)

**Comment by eduramiba** [comment]
It seems you don't have the proper drivers + cuda 10.0 installation to show `nvidia-smi`.

This is my usual script to do it in ubuntu 18.04:

```bash
# Nvidia drivers
sudo apt install build-essential dkms gcc-multilib
wget http://es.download.nvidia.com/XFree86/Linux-x86_64/430.50/NVIDIA-Linux-x86_64-430.50.run
sudo chmod +x NVIDIA-Linux-x86_64-430.50.run
sudo ./NVIDIA-Linux-x86_64-430.50.run --dkms -s --no-cc-version-check
rm NVIDIA-Linux-x86_64-430.14.run

# Install CUDA 10.0 (until tensorflow supports 10.1)

wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux
sudo sh cuda_10.0.130_410.48_linux --silent
wget http://developer.download.nvidia.com/compute/cuda/10.0/Prod/patches/1/cuda_10.0.130.1_linux.run
sudo sh cuda_10.0.130.1_linux.run --silent
rm cuda_*

# Install CUDNN
#download cudnn-10.0-linux-x64-v7.6.4.38.tgz manually, you need to login: https://developer.nvidia.com/cudnn
tar -xzvf cudnn-10.0-linux-x64-v7.6.4.38.tgz
sudo cp cuda/include/cudnn.h /usr/local/cuda-10.0/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda-10.0/lib64
sudo chmod a+r /usr/local/cuda-10.0/include/cudnn.h /usr/local/cuda-10.0/lib64/libcudnn*
sudo rm -r cuda
rm cudnn*

# Conda python
wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
sh Miniconda2-latest-Linux-x86_64.sh
rm Miniconda2-latest-Linux-x86_64.sh

echo 'export PATH="/home/youruser/miniconda2/bin:$PATH"' >> /home/youruser/bashrc
echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64"' >> /home/youruser/.zshrc

# Create tensorflow env
conda create --name tensorflow python=3.7
source activate tensorflow
pip install tensorflow-gpu
```

**Comment by jgraving** [comment]
The error appears to be some internal Tensorflow issue with using the CPU, which I can't help you with. @eduramiba's script should work to install the GPU version of Tensorflow with Anaconda if you have a Nvidia GPU. Also check the official Tensorflow installation guide: https://www.tensorflow.org/install/gpu

**Comment by Philip642** [comment]
Thanks, I'll try that and it looks like I have an Intel and an Nvidia GPU
![Screenshot from 2019-10-10 14-19-11](https://user-images.githubusercontent.com/55141900/66568215-47310880-eb69-11e9-9231-83b013584f71.png)

**Comment by Philip642** [comment]
Some lines didn't work (like sudo sh cuda_10.0.130_410.48_linux --silent or sudo cp cuda/include/cudnn.h /usr/local/cuda-10.0/include) and now I can't start the navigator or the other environments although their there
![conda](https://user-images.githubusercontent.com/55141900/66646734-51194100-ec27-11e9-86d5-a639ec561fb9.png)

**Comment by jgraving** [comment]
`(base)` suggests you're already inside the conda base environment. I don't think you can activate another environment if you're already in one.
Try:
```bash
conda deactivate
conda activate tensorflow
```
Or:
```bash
source ~/.profile
conda activate tensorflow
```

Make sure to download cudnn manually as the script says. This is the script I used for my Ubuntu workstation (just replace the last part with installation with anaconda): https://gist.github.com/Mahedi-61/2a2f1579d4271717d421065168ce6a73
