### ISSUE TITLE
how to create the h5 file for our own dataset?

### ISSUE THREAD

**Issue by monajalal** [jgraving/DeepPoseKit#14]
I am in this step of the step1***.ipynb notebook.
How should I create my own h5 for my own dataset?

![Screenshot from 2019-10-22 20-58-56](https://user-images.githubusercontent.com/1892917/67347062-004ef580-f50f-11e9-8794-35d4c8943fdb.png)

**Comment by jgraving** [comment]
The `initialize_dataset` function takes a set of images as a numpy array and a skeleton and then initializes the .h5 file for annotating in step 2. [See the docs](http://jakegraving.com/DeepPoseKit/html/deepposekit/io/utils.html#initialize_dataset) for more details
