### ISSUE TITLE
Provide more details for using annotation GUI

### ISSUE THREAD

**Issue by monajalal** [jgraving/DeepPoseKit#15]
I am rather lost trying to figure how to assiciate the keypoints to the names saved in skeleton.csv file? could you please create a video that tells this in more detail or show a more detailed manual?

![Screenshot from 2019-10-22 21-06-14](https://user-images.githubusercontent.com/1892917/67347435-0a252880-f510-11e9-883e-c9e8be5bb9ee.png)

**Comment by monajalal** [comment]
also, when I tried to use my own dataset, here is what I get as error:

![Screenshot from 2019-10-22 21-16-09](https://user-images.githubusercontent.com/1892917/67347845-4442fa00-f511-11e9-89b3-633cebb58f28.png)

![Screenshot from 2019-10-22 21-17-19](https://user-images.githubusercontent.com/1892917/67347872-5cb31480-f511-11e9-899f-d75c1099d880.png)

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-4727fc8a3778> in <module>()
      3                 skeleton='/scratch3/3d_pose/animalpose/DeepPoseKit/datasets/moth/skeleton.csv',
      4                 shuffle_colors=False,
----> 5                 text_scale=0.2)

/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/deepposekit/annotate/gui/Annotator.py in __init__(self, datapath, dataset, skeleton, scale, text_scale, shuffle_colors, refresh)
    122         self._init_skeleton(skeleton)
    123         if os.path.exists(datapath):
--> 124             self._init_data(datapath, dataset)
    125         else:
    126             raise ValueError("datapath file or path does not exist")

/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/deepposekit/annotate/gui/Annotator.py in _init_data(self, datapath, dataset)
    154         with h5py.File(self.datapath, "r+") as h5file:
    155 
--> 156             self.n_images = h5file[self.dataset].shape[0]
    157             # Check that all parts of the file exist
    158             if "annotations" not in list(h5file.keys()):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/scratch/sjn-p3/anaconda/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    165                 raise ValueError("Invalid HDF5 object reference")
    166         else:
--> 167             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    168 
    169         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'images' doesn't exist)"

```

**Comment by jgraving** [comment]
Can you provide further details of what you mean? The highlighted keypoint name and the crosshair correspond to one another (e.g. in the image your provided `head` corresponds to the crosshair keypoint in the GUI) And the navigation hotkeys shown in the notebook let you annotate the images with the keypoints defined in the skeleton file. 

It looks like the h5 file (`datasets/moth/example_annotation_set.h5`) you are pointing it to doesn't contain any images. Did you successfully load the images at the end of step 1? If you are using data from DeepLabCut, only model training (step 3) is currently supported, but we are working on an update to add annotations as well.

**Comment by monajalal** [comment]
I think it is quite hard for me to follow the instructions.

So, I am trying to annotate my own data which I have png images for.
I also created a numpy array.

It is totally unclear for me how you create the example_annotation.h5 file or what is the 'images' string that you have in your code. I pass it a numpy array, it tells me it should be string. I pass it the path to the png images, it gives me another error.

Could you please kindly guide me on:

1. how to create the example_annotation.h5 file? If you could share your own script, would be awesome.
2. what is your script to create a numpy array?
3. How does the data from step1 is readable in step2? aren't these two different datasets?
4. If you could make it rather crystal clear what is the difference between notebook 1 (step1..) and notebook 2 (step2...)?
![Screenshot from 2019-10-27 15-50-14](https://user-images.githubusercontent.com/1892917/67640658-348d3200-f8d2-11e9-8ba7-0af37741fdcc.png)


![Screenshot from 2019-10-27 15-46-58](https://user-images.githubusercontent.com/1892917/67640659-3951e600-f8d2-11e9-87fa-a346d9cff1d0.png)


![Screenshot from 2019-10-27 15-50-49](https://user-images.githubusercontent.com/1892917/67640660-3e169a00-f8d2-11e9-8704-cf607f98843d.png)
