### ISSUE TITLE
how should we move to the next keypoint in the annotation process?

### ISSUE THREAD

**Issue by monajalal** [jgraving/DeepPoseKit#18]
currently, when I open the annotation GUI, it starts with head, but doesn't move to other keypoints.

![Screenshot from 2019-10-27 17-16-59](https://user-images.githubusercontent.com/1892917/67642013-de25f080-f8dd-11e9-8a70-3bb386ff4bcf.png)

How can I move to the next keypoint or how can we make the selection for one keypoint finalized?

![Screenshot from 2019-10-27 17-19-57](https://user-images.githubusercontent.com/1892917/67642028-10375280-f8de-11e9-995c-a907c94e44d5.png)

p.s. Does wingR or WingL need to be a parent of head? I am CS major not animal sciences so I wonder how do you define parents in your field.

I am also seeing this:

```
QObject::moveToThread: Current thread (0x4b1ebf0) is not the object's thread (0x4bbf1f0).
Cannot move to target thread (0x4b1ebf0)
```

When I change the skeleton.csv to the following:

![Screenshot from 2019-10-27 17-50-07](https://user-images.githubusercontent.com/1892917/67642444-3e1e9600-f8e2-11e9-9db2-1b8e1348bbb1.png)

I get to see this, still not able to finalize the head keypoint to move to the next keypoint in the image.

![Screenshot from 2019-10-27 17-49-07](https://user-images.githubusercontent.com/1892917/67642437-30691080-f8e2-11e9-840a-7277e686bd99.png)

**Comment by jgraving** [comment]
Are you saying the hotkeys for changing keypoints don't work? <kbd>I</kbd>,<kbd>K</kbd> or <kbd>tab</kbd>, <kbd>shift</kbd>+<kbd>tab</kbd> = switch active keypoint

If the hotkeys aren't working then I'm afraid it's likely a problem with opencv, and there is not much I can do. I would make sure you have a recent version installed with:
 ```bash
pip install --upgrade opencv-python
```

Once you've annotated all the keypoints in one frame then the keypoints and skeleton should turn blue. `parent` is not a specific term to the "animal sciences", it's describing the hierarchical structure of posture graph. The reason for adding this information is described in the paper (http://paper.deepposekit.org or http://preprint.deepposekit.org)

**Comment by monajalal** [comment]
awesome, I didn't know about "tab" shortcut.
