### ISSUE TITLE
Not all joints are shown

### ISSUE THREAD

**Issue by monajalal** [jgraving/DeepPoseKit#19]
In some frames, not all joints are shown. How can I make it work better? For the below examples, it should show 4 keypoints.

![Screenshot from 2019-10-28 14-11-04](https://user-images.githubusercontent.com/1892917/67705174-e2f5ad80-f98c-11e9-8818-da8bb44cc42e.png)
![Screenshot from 2019-10-28 14-09-56](https://user-images.githubusercontent.com/1892917/67705175-e2f5ad80-f98c-11e9-8cbb-a9132664bd19.png)
![Screenshot from 2019-10-28 14-09-37](https://user-images.githubusercontent.com/1892917/67705176-e38e4400-f98c-11e9-9d4b-16a655e363e0.png)

**Comment by jgraving** [comment]
I'm confused. It's showing all 4 keypoints in both images. The right wing is near the edge in top image, so it's partially cut off (possibly due to image augmentation), but this is normal behavior.
