### ISSUE TITLE
I couldn't import Deepposekit

### ISSUE THREAD

**Issue by vickyhexr** [jgraving/DeepPoseKit#2]
Hey. I've installed all dependencies and cloned complete things. when i open the project in jupyter-lab i couldn't import deepposekit. Please help me out

**Comment by jgraving** [comment]
Can you provide more details such as the error message and what OS (Ubuntu, Windows, etc.) and python environment (Anaconda, pip, python3, etc.) you're using?

**Comment by vickyhexr** [comment]
Hey, I am using Windows 10. 
Python environment is pip.
I've  installed Keras and Tensorflow GPU as well.
Cloned deepposekit from git.
![Capture](https://user-images.githubusercontent.com/51114027/60888935-7d62a180-a275-11e9-8f29-6fd987fec8b8.JPG)

This is the error when i try to import deepposekit.

**Comment by jgraving** [comment]
Hi, thanks for the details. ModuleNotFoundError means you have not installed the deepposekit package or python cannot find it in the site-packages directory. You say you "Cloned deepposekit from git", but did you [follow the installation instructions](https://github.com/jgraving/deepposekit/blob/master/README.md#installation)? Alternatively you can install directly in jupyter by running:
```python
import sys
!{sys.executable} -m pip install git+https://www.github.com/jgraving/deepposekit.git git+https://www.github.com/jgraving/deepposekit-annotator.git
```

**Comment by vickyhexr** [comment]
Hi, thanks for the quick reply. I think i followed the instructions completely and it didn't throw any error.  Anyways i tried it by using jupyter by using  
**import sys
!{sys.executable} -m pip install git+https://www.github.com/jgraving/deepposekit.git git+https://www.github.com/jgraving/deepposekit-annotator.git** these lines. Still it has error itseems.

![Capture](https://user-images.githubusercontent.com/51114027/60890817-b0a72f80-a279-11e9-8f7b-3071d26ce43a.JPG)

**Comment by jgraving** [comment]
Looks like you're using anaconda on Windows, which we don't fully support yet. It seems the Shapely dependency for imgaug cannot be installed on windows with pip. Can you try installing imgaug using conda?
```bash
conda config --add channels conda-forge
conda install imgaug
```
Alternatively you can try installing Shapely with pip using a pre-compiled wheel found here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely then run:
```bash
pip install /path/to/wheel/file.whl
```
and replace the path with where your wheel file is stored

**Comment by vickyhexr** [comment]
After installing imgaug i couldn't import deepposekit. Is there any issues with Windows?

**Comment by jgraving** [comment]
We are working on a better solution for windows and anaconda. Once imgaug is installed then you should be able to install deepposekit from jupyter without any errors:

> ```python
> import sys
> !{sys.executable} -m pip install git+https://www.github.com/jgraving/deepposekit.git git+https://www.github.com/jgraving/deepposekit-annotator.git
> ```

**Comment by vickyhexr** [comment]
Hey buddy. I think i have a problem with shapely and imgaug. Can i use Python 3.6? I got this doubt suddenly. Do you have any requirements.txt for deepposekit?? If yes can you post it here?? Thanks in advance.

**Comment by vickyhexr** [comment]
I've re-installed everything and its working now. I am able to import deepposekit now. My next question is,Can i use this library for human pose estimation?

**Comment by jgraving** [comment]
Hi, Glad you got it working. You can use deepposekit for human pose estimation, but we do not provide any pretrained models, so you'll need to provide your own training data. I'll leave this issue open for now until we implement a better solution for your original problem.

**Comment by vickyhexr** [comment]
Thanks for the reply, Jake.

**Comment by jgraving** [comment]
After further research it seems this issue is specific to Anaconda on Windows. It appears the `Shapely` dependency for `imgaug` must be manually installed. I've updated the readme here: https://github.com/jgraving/DeepPoseKit#installing-with-anaconda-on-windows 
So, I'll go ahead and close this.
