### ISSUE TITLE
How can I use the expert annotation for my dataset for using DeepPoseKit?

### ISSUE THREAD

**Issue by monajalal** [jgraving/DeepPoseKit#22]
[moth_annotations_pts.txt](https://github.com/jgraving/DeepPoseKit/files/3785248/moth_annotations_pts.txt)
I have expert annotations for my dataset. I am wondering how I could directly feed them into training rather than annotating the dataset myself?

Each line of my annotated data is like:
1.0000  494.5551  234.2510  711.6219  274.2668  481.7198  299.5598  311.0864  339.5756

where 1.0000 represents the frame number, followed by x and y for 4 key points of a moth.

**Comment by jgraving** [comment]
You can write a custom `DataGenerator`. See https://github.com/jgraving/DeepPoseKit/blob/master/examples/custom_data_generator.ipynb
