### ISSUE TITLE
Issue with zooming, using separate image for keypoint annotation

### ISSUE THREAD

**Issue by subhacom** [jgraving/DeepPoseKit#37]
When trying to use the annotator GUI to mark the keypoints and zooming the frame, I could not find a way to scroll the image to have the target object within the visible section of the window. Are there some shortcuts for scrolling (I could not find any in the documentation).
Alternatively, I can crop the original frame to the area where the target object is visible. In the `deepposekit-data/datasets/locust`, I notice such an image of a single object (`skeleton_image.png`). But I have not yet been able to figure out how to use that with the annotator.
It will be helpful to show an example of using this for annotation.

**Comment by jgraving** [comment]
You should be able to zoom with +- keys and drag the window or you can use the scroll wheel to zoom to a specific part of the image with the GUI interface. But generally if your image is too large to fit on the screen and annotate without scrolling then it's probably too large for training a model. If you can crop the images then you should do that as it will be much faster.

**Comment by Selmaan** [comment]
For my use case, I am tracking an animal that is freely moving within a larger arena, and so it is not trivial to crop the video around the subject.

Being able to zoom in to a specific region using the scroll wheel sounds like a great solution. However it does not appear to function, at least on Windows 10
