### ISSUE TITLE
PyYAML dependency

### ISSUE THREAD

**Issue by Selmaan** [jgraving/DeepPoseKit#40]
It appears like this code requires installation of the PyYAML package, but this is not properly listed in requirements. 

After installing deep pose kit following instructions, importing the package results in the error:
`ModuleNotFoundError: No module named 'yaml'`

manually doing 
`pip install pyyaml`

fixes this

**Comment by jgraving** [comment]
Thanks for pointing this out. If you want to submit a PR to update setup.py I'd appreciate it. Otherwise I'll add this later when I have time to push some updates.

**Comment by Selmaan** [comment]
I submitted a PR to update this a few days back.

**Comment by jgraving** [comment]
Thanks! Sorry I was traveling and just got back to work.
