### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.applications.imagenet_utils' has no attribute 'imagenet_utils'

### ISSUE THREAD

**Issue by omkarap55** [jgraving/DeepPoseKit#47]
Getting following error on running 2nd cell from [this notebook](https://colab.research.google.com/github/jgraving/deepposekit/blob/master/examples/step3_train_model.ipynb) 
![image](https://user-images.githubusercontent.com/17846063/78879620-c3050280-7a71-11ea-9deb-a84c9cebc680.png)

**Comment by jgraving** [comment]
Nasty bug. Thanks for reporting it. Working on a fix, but it's a bit more complex than I thought.

**Comment by jgraving** [comment]
Latest version should fix this. Reopen it if you still run into problems
