### ISSUE TITLE
object 'images' doesn't exist

### ISSUE THREAD

**Issue by Philip642** [jgraving/DeepPoseKit#6]
![Screenshot from 2019-09-10 14-42-30](https://user-images.githubusercontent.com/55141900/64614809-9a346600-d3d9-11e9-9257-59e0e64321f4.png)

**Comment by jgraving** [comment]
Hi, Can you provide more details? What system are you running this on? What file is `annotation_sets[1]`? Is it one of the example datasets or a custom dataset that you made?

**Comment by Philip642** [comment]
Hi, It's on the recommended Ubuntu system 18.04 and with your example files. I just changed the directorys. annotation_sets[1] was there from you, I don't know what file that is and wasn't able to figure that out...

**Comment by jgraving** [comment]
can you try this?

```python
print(annotation_sets[1])
```

You could also manually provide the `datapath` such as `datapath="/path/to/file.h5"` to make sure it's pointing to the correct file.

**Comment by Philip642** [comment]
print(annotation_sets[1]) is: fly/log_densenet.h5
print(annotation_sets[2]) is: best_model_densenet.h5
print(annotation_sets[3]) is: example_annotation_set.h5
print(annotation_sets[4]) is: annotation_data_release.h5
and it works with 3 and 4, with 1 and2 I get the same error messages

**Comment by jgraving** [comment]
`log_densenet.h5` is a training log
`best_model_densenet.h5` is a saved model
If you try to load these as a dataset then you'll get an error. I will update the examples so this is clearer.

**Comment by Philip642** [comment]
Ok, thanks
