### ISSUE TITLE
Error in Step 3 iPython notebook on Google Collab - AttributeError: 'StackedDenseNet' object has no attribute 'distribute_strategy'

### ISSUE THREAD

**Issue by jonmatthis** [jgraving/DeepPoseKit#69]
![image](https://user-images.githubusercontent.com/15314521/99986156-d81e6f80-2d7c-11eb-898a-30c50e200a02.png)

I tried rolling back tensorflow to verson 2.2.0 per issue #62  (https://github.com/jgraving/DeepPoseKit/issues/62), but that did not help

**Comment by Funkyojo** [comment]
I had the same issue today.
After some trouble shooting, I believe the error comes from "model_checkpoint" in callbacks. 
Which I don't think is necessary..... So you can leave that out in your callbacks.
You can then add "restore_best_weights=True" in your EarlyStopping(...) to achieve the same thing.
