### ISSUE TITLE
DeepPoseKit Step 2 - Annotate your data GUI Error in _save()

### ISSUE THREAD

**Issue by jks5177** [jgraving/DeepPoseKit#76]
I used the jupyter notebook to execute it. 
If you press the "q" button in the GUI environment, the error as shown below occurs. 
Please solve this problem. Thank you!
![error_1](https://user-images.githubusercontent.com/53725808/106991207-1abaea00-67b9-11eb-9142-b48b60291469.jpg)

**Comment by DVsilva98** [comment]
Hi, I'm having the same problem. Did you find a way to fix it? Thanks.
