### ISSUE TITLE
An unsolvable error when I try to use the DataGenerator.

### ISSUE THREAD

**Issue by Hetav01** [jgraving/DeepPoseKit#90]
Please help me out here!!!!!

I am trying to use the DataGenerator with a .h5 file and it is constantly throwing me this error:

<img width="1028" alt="Screenshot 2022-09-05 at 13 01 01" src="https://user-images.githubusercontent.com/53979508/188393764-dcee295a-d271-4253-b14e-db9f56084245.png">

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [60], in <cell line: 1>()
----> 1 data_generator = DataGenerator('GodSpeed/example_annotation_set.h5')
      3 image, keypoints = data_generator[0]
      5 plt.figure(figsize=(5,5))

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/deepposekit/io/DataGenerator.py:81, in DataGenerator.__init__(self, datapath, dataset, mode, **kwargs)
     79 else:
     80     self.mode = mode
---> 81 self.annotated = np.all(h5file["annotated"].value, axis=1)
     82 self.annotated_index = np.where(self.annotated)[0]
     83 self.n_annotated = self.annotated_index.shape[0]

AttributeError: 'Dataset' object has no attribute 'value'

**Comment by 71c** [comment]
I found a solution. See my comment on #83.
